import { isSafeSlugSegment } from '@zeropress/slug-policy';
import { canonicalizeTimeZone } from './time.js';
import {
  hasCredentialAuthority,
  hasQueryOrFragment,
  hasUnsafeUrlCharacters,
  normalizeHttpOrigin,
  normalizeHttpUrlPrefix,
  parseSafeHttpUrl,
} from './url.js';

const BASE_SCHEMA_REFERENCE = 'https://schemas.zeropress.dev/wxr-import-base/v0.7/schema.json';
const CUSTOM_HTML_SLOT_MAX_CODE_POINTS = 65536;
const BASE_TOP_LEVEL_KEYS = new Set([
  '$schema', 'version', 'site', 'meta', 'newsletter', 'comments', 'widgets', 'collections', 'custom_css', 'custom_html', 'import',
]);
const BASE_SITE_KEYS = new Set([
  'title',
  'description',
  'url',
  'media_origin',
  'media_delivery_mode',
  'favicon',
  'logo',
  'expose_generator',
  'search',
  'feed',
  'archive',
  'locale',
  'posts_per_page',
  'date_style',
  'time_style',
  'timezone',
  'robots',
  'permalinks',
  'front_page',
  'post_index',
  'footer',
]);
export const PERMALINK_FIELDS = Object.freeze(['posts', 'pages', 'categories', 'tags']);
const PERMALINK_TOKENS = Object.freeze({
  posts: new Set(['slug', 'public_id', 'year', 'month', 'day']),
  pages: new Set(['slug']),
  categories: new Set(['slug']),
  tags: new Set(['slug']),
});
const DEFAULT_WIDGETS = Object.freeze({
  sidebar: Object.freeze({
    name: 'Sidebar Widgets',
    items: Object.freeze([
      Object.freeze({
        type: 'search',
        title: 'Search',
        settings: Object.freeze({
          placeholder: 'Search...',
          button_label: 'Search',
        }),
      }),
      Object.freeze({
        type: 'recent-posts',
        title: 'Recent Posts',
        settings: Object.freeze({
          limit: 5,
          show_date: true,
        }),
      }),
      Object.freeze({
        type: 'categories',
        title: 'Categories',
        settings: Object.freeze({
          show_count: false,
          hierarchical: false,
        }),
      }),
      Object.freeze({
        type: 'tags',
        title: 'Tags',
        settings: Object.freeze({
          limit: 20,
          show_count: false,
        }),
      }),
      Object.freeze({
        type: 'archives',
        title: 'Archives',
        settings: Object.freeze({
          limit: 12,
        }),
      }),
    ]),
  }),
});

export function createBaseWidgets(value) {
  return value === undefined
    ? structuredClone(DEFAULT_WIDGETS)
    : structuredClone(value);
}

export function createResolvedBase({ baseData, site, widgets, configuredMediaOrigin }) {
  const resolvedSite = structuredClone(site);
  resolvedSite.media_origin = configuredMediaOrigin;
  const resolvedBase = {
    $schema: BASE_SCHEMA_REFERENCE,
    version: '0.7',
    site: resolvedSite,
  };

  if (resolvedSite.meta !== undefined) {
    resolvedBase.meta = resolvedSite.meta;
    delete resolvedSite.meta;
  }
  if (resolvedSite.newsletter !== undefined) {
    resolvedBase.newsletter = resolvedSite.newsletter;
    delete resolvedSite.newsletter;
  }
  if (resolvedSite.comments !== undefined) {
    resolvedBase.comments = resolvedSite.comments;
    delete resolvedSite.comments;
  }
  resolvedBase.widgets = structuredClone(widgets);
  if (baseData.collections !== undefined) {
    resolvedBase.collections = structuredClone(baseData.collections);
  }
  if (baseData.custom_css !== undefined) {
    resolvedBase.custom_css = baseData.custom_css;
  }
  if (baseData.custom_html !== undefined) {
    resolvedBase.custom_html = structuredClone(baseData.custom_html);
  }
  if (baseData.import !== undefined) {
    resolvedBase.import = structuredClone(baseData.import);
  }

  return resolvedBase;
}

export function normalizeBase(base) {
  if (!isRecord(base)) {
    throw new Error('Invalid base JSON: expected an object');
  }
  const forbiddenKeys = ['preview_data', 'content', 'menus', 'generator', 'generated_at'];
  for (const key of forbiddenKeys) {
    if (base[key] !== undefined) {
      throw new Error(`Invalid base JSON: ${key} is generated by wxr-import and cannot be provided in the base file`);
    }
  }
  for (const key of Object.keys(base)) {
    if (!BASE_TOP_LEVEL_KEYS.has(key)) {
      throw new Error(`Invalid base JSON: unknown top-level key ${key}`);
    }
  }

  if (base.version !== '0.7') {
    throw new Error('Invalid base JSON: version must be exactly "0.7"');
  }
  validateOptionalString(base.$schema, '$schema');
  validateBaseSite(base.site);
  validateBaseMeta(base.meta);
  validateBaseNewsletter(base.newsletter);
  const normalizedComments = validateAndNormalizeBaseComments(base.comments);
  for (const key of ['widgets', 'collections']) {
    validateOptionalRecord(base[key], key);
  }
  validateCustomCss(base.custom_css);
  validateCustomHtml(base.custom_html);
  const normalizedImport = validateAndNormalizeImport(base.import);

  const normalized = structuredClone(base);
  if (normalized.site !== undefined) {
    normalized.site.media_origin = normalizeMediaOrigin(normalized.site.media_origin ?? '', 'site.media_origin');
    if (Object.hasOwn(normalized.site, 'url')) {
      normalized.site.url = normalizeSiteOrigin(normalized.site.url, 'site.url');
    }
    if (Object.hasOwn(normalized.site, 'locale')) {
      normalized.site.locale = normalizeLocale(normalized.site.locale, 'site.locale');
    }
    if (Object.hasOwn(normalized.site, 'timezone')) {
      normalized.site.timezone = normalizeExplicitTimeZone(normalized.site.timezone);
    }
    if (normalized.site.media_delivery_mode === 'media_domain' && !normalized.site.media_origin) {
      throw new Error('Invalid base JSON: site.media_origin must be non-empty when site.media_delivery_mode is "media_domain"');
    }
  }
  if (normalizedImport !== undefined) normalized.import = normalizedImport;
  if (normalizedComments !== undefined) normalized.comments = normalizedComments;
  return normalized;
}

export function inferMediaOriginFromImport(importOptions) {
  if (!isRecord(importOptions) || typeof importOptions.media_to !== 'string') {
    return '';
  }
  try {
    return new URL(importOptions.media_to).origin;
  } catch {
    return '';
  }
}

function validateBaseSite(site) {
  if (site === undefined) return;
  validateOptionalRecord(site, 'site');
  if (Object.hasOwn(site, 'comments')) {
    throw new Error('Invalid base JSON: site.comments is not accepted; use top-level comments instead');
  }
  if (Object.hasOwn(site, 'meta')) {
    throw new Error('Invalid base JSON: site.meta is not accepted; use top-level meta instead');
  }
  if (Object.hasOwn(site, 'newsletter')) {
    throw new Error('Invalid base JSON: site.newsletter is not accepted; use top-level newsletter instead');
  }
  if (Object.hasOwn(site, 'media_base_url')) {
    throw new Error('Invalid base JSON: site.media_base_url is not supported; use site.media_origin');
  }
  if (Object.hasOwn(site, 'disallow_comments')) {
    throw new Error('Invalid base JSON: site.disallow_comments is not supported; use top-level comments.enabled');
  }
  if (Object.hasOwn(site, 'indexing')) {
    throw new Error('Invalid base JSON: site.indexing is not supported; use site.robots.allow_indexing');
  }
  for (const key of Object.keys(site)) {
    if (!BASE_SITE_KEYS.has(key)) {
      throw new Error(`Invalid base JSON: unknown site key ${key}`);
    }
  }

  for (const key of ['title', 'description', 'url', 'media_origin', 'media_delivery_mode', 'locale', 'date_style', 'time_style', 'timezone']) {
    validateOptionalString(site[key], `site.${key}`);
  }
  if (site.media_delivery_mode !== undefined && !['none', 'media_domain'].includes(site.media_delivery_mode)) {
    throw new Error('Invalid base JSON: site.media_delivery_mode must be one of none, media_domain');
  }
  for (const key of ['date_style', 'time_style']) {
    if (site[key] !== undefined && !['none', 'short', 'medium', 'long', 'full'].includes(site[key])) {
      throw new Error(`Invalid base JSON: site.${key} must be one of none, short, medium, long, full`);
    }
  }
  validateOptionalBoolean(site.expose_generator, 'site.expose_generator');
  validateOptionalInteger(site.posts_per_page, 'site.posts_per_page', { minimum: 1 });
  for (const key of ['favicon', 'logo', 'front_page', 'post_index', 'footer']) {
    validateOptionalRecord(site[key], `site.${key}`);
  }
  if (site.robots !== undefined) {
    validateClosedRecord(site.robots, 'site.robots', ['allow_indexing']);
    if (!Object.hasOwn(site.robots, 'allow_indexing')) {
      throw new Error('Invalid base JSON: site.robots.allow_indexing is required when site.robots is provided');
    }
    validateOptionalBoolean(site.robots.allow_indexing, 'site.robots.allow_indexing');
  }
  for (const key of ['search', 'feed', 'archive']) {
    validateBaseFeatureToggle(site[key], `site.${key}`);
  }
  if (site.permalinks !== undefined) {
    validateClosedRecord(site.permalinks, 'site.permalinks', ['output_style', ...PERMALINK_FIELDS]);
    if (site.permalinks.output_style !== undefined && !['directory', 'html-extension'].includes(site.permalinks.output_style)) {
      throw new Error('Invalid base JSON: site.permalinks.output_style must be one of directory, html-extension');
    }
    for (const field of PERMALINK_FIELDS) {
      const pattern = site.permalinks[field];
      validateOptionalString(pattern, `site.permalinks.${field}`);
      if (pattern !== undefined) validateBasePermalinkPattern(pattern, field);
    }
  }
}

function validateBaseMeta(meta) {
  if (meta === undefined) return;
  validateOptionalRecord(meta, 'meta');
}

function validateAndNormalizeBaseComments(comments) {
  if (comments === undefined) return undefined;
  validateClosedRecord(comments, 'comments', ['enabled', 'provider', 'api_base_url', 'per_page', 'order', 'threading']);
  if (!Object.hasOwn(comments, 'api_base_url')) {
    throw new Error('Invalid base JSON: comments.api_base_url is required when comments is provided');
  }
  validateOptionalBoolean(comments.enabled, 'comments.enabled');
  if (comments.provider !== undefined && comments.provider !== 'wordpress') {
    throw new Error('Invalid base JSON: comments.provider must be wordpress');
  }
  validateOptionalInteger(comments.per_page, 'comments.per_page', { minimum: 1, maximum: 100 });
  if (comments.order !== undefined && !['asc', 'desc'].includes(comments.order)) {
    throw new Error('Invalid base JSON: comments.order must be one of asc, desc');
  }

  let normalizedThreading;
  if (comments.threading !== undefined) {
    validateClosedRecord(comments.threading, 'comments.threading', ['enabled', 'max_depth']);
    validateOptionalBoolean(comments.threading.enabled, 'comments.threading.enabled');
    validateOptionalInteger(comments.threading.max_depth, 'comments.threading.max_depth', { minimum: 2, maximum: 10 });
    normalizedThreading = structuredClone(comments.threading);
  }

  return {
    ...(comments.enabled !== undefined ? { enabled: comments.enabled } : {}),
    ...(comments.provider !== undefined ? { provider: comments.provider } : {}),
    ...(comments.api_base_url !== undefined
      ? { api_base_url: normalizeCommentsApiBaseUrl(comments.api_base_url, 'comments.api_base_url') }
      : {}),
    ...(comments.per_page !== undefined ? { per_page: comments.per_page } : {}),
    ...(comments.order !== undefined ? { order: comments.order } : {}),
    ...(normalizedThreading !== undefined ? { threading: normalizedThreading } : {}),
  };
}

function validateBaseFeatureToggle(value, field) {
  if (value === undefined) return;
  validateClosedRecord(value, field, ['enabled']);
  if (!Object.hasOwn(value, 'enabled')) {
    throw new Error(`Invalid base JSON: ${field}.enabled is required`);
  }
  validateOptionalBoolean(value.enabled, `${field}.enabled`);
}

function validateBaseNewsletter(newsletter) {
  if (newsletter === undefined) return;
  validateClosedRecord(newsletter, 'newsletter', [
    'enabled', 'title', 'description', 'button_label', 'signup_url', 'embed_url',
  ]);
  validateOptionalBoolean(newsletter.enabled, 'newsletter.enabled');
  for (const key of ['title', 'description', 'button_label', 'signup_url', 'embed_url']) {
    validateOptionalString(newsletter[key], `newsletter.${key}`);
  }
}

function validateCustomCss(customCss) {
  if (customCss === undefined) return;
  validateClosedRecord(customCss, 'custom_css', ['content']);
  if (typeof customCss.content !== 'string' || customCss.content.trim() === '') {
    throw new Error('Invalid base JSON: custom_css.content must be a non-empty string');
  }
}

function validateCustomHtml(customHtml) {
  if (customHtml === undefined) return;
  validateClosedRecord(customHtml, 'custom_html', ['head_end', 'body_end']);
  const slots = ['head_end', 'body_end'].filter((slot) => Object.hasOwn(customHtml, slot));
  if (slots.length === 0) {
    throw new Error('Invalid base JSON: custom_html must include head_end or body_end');
  }
  for (const slot of slots) {
    const value = customHtml[slot];
    if (typeof value !== 'string' || value.trim() === '') {
      throw new Error(`Invalid base JSON: custom_html.${slot} must be a non-empty string`);
    }
    if ([...value].length > CUSTOM_HTML_SLOT_MAX_CODE_POINTS) {
      throw new Error(
        `Invalid base JSON: custom_html.${slot} must be at most ${CUSTOM_HTML_SLOT_MAX_CODE_POINTS} Unicode code points`,
      );
    }
  }
}

function validateAndNormalizeImport(importOptions) {
  if (importOptions === undefined) return undefined;
  validateClosedRecord(importOptions, 'import', ['media_from', 'media_to']);
  const hasFrom = Object.hasOwn(importOptions, 'media_from');
  const hasTo = Object.hasOwn(importOptions, 'media_to');
  if (hasFrom !== hasTo) {
    throw new Error('Invalid base JSON: import.media_from and import.media_to must be provided together');
  }
  if (!hasFrom) return {};
  return {
    media_from: normalizeMediaPrefix(importOptions.media_from, 'import.media_from'),
    media_to: normalizeMediaPrefix(importOptions.media_to, 'import.media_to'),
  };
}

function normalizeMediaPrefix(value, path) {
  const normalized = normalizeHttpUrlPrefix(value);
  if (!normalized) {
    throw new Error(
      `Invalid base JSON: ${path} must be an absolute HTTP(S) URL prefix without credentials, query, or fragment`,
    );
  }
  return normalized;
}

function normalizeMediaOrigin(value, path) {
  if (value === '') return '';
  const origin = normalizeHttpOrigin(value);
  if (!origin) {
    throw new Error(
      `Invalid base JSON: ${path} must be an empty string or an absolute HTTP(S) origin without credentials, path, query, or fragment`,
    );
  }
  return origin;
}

function validateBasePermalinkPattern(pattern, field) {
  const path = `site.permalinks.${field}`;
  if (pattern.trim() === '' || pattern.trim() !== pattern || !pattern.startsWith('/')) {
    throw new Error(`Invalid base JSON: ${path} must be a non-empty absolute path pattern`);
  }
  if (pattern.includes('\\') || pattern.includes('?') || pattern.includes('#') || pattern.includes('%') || /[\s\u0000-\u001F\u007F]/.test(pattern)) {
    throw new Error(`Invalid base JSON: ${path} contains an unsafe character`);
  }
  if (pattern.endsWith('.html') || pattern.includes('.html/')) {
    throw new Error(`Invalid base JSON: ${path} must not contain a literal .html suffix`);
  }

  const body = pattern.replace(/^\/+|\/+$/g, '');
  const segments = body.split('/');
  if (!body || segments.some((segment) => segment === '')) {
    throw new Error(`Invalid base JSON: ${path} must contain non-empty path segments`);
  }
  const usedTokens = new Set();
  for (const segment of segments) {
    if (segment.includes(':')) {
      if (!segment.startsWith(':') || segment.slice(1).includes(':') || segment.length === 1) {
        throw new Error(`Invalid base JSON: ${path} tokens must occupy a full path segment`);
      }
      const token = segment.slice(1);
      if (!PERMALINK_TOKENS[field].has(token)) {
        throw new Error(`Invalid base JSON: ${path} has unsupported token :${token}`);
      }
      usedTokens.add(token);
      continue;
    }
    if (!isSafeSlugSegment(segment)) {
      throw new Error(`Invalid base JSON: ${path} contains an unsafe path segment`);
    }
  }
  if (field === 'posts' && !usedTokens.has('slug') && !usedTokens.has('public_id')) {
    throw new Error(`Invalid base JSON: ${path} must include :slug or :public_id`);
  }
  if (field !== 'posts' && !usedTokens.has('slug')) {
    throw new Error(`Invalid base JSON: ${path} must include :slug`);
  }
}

function validateClosedRecord(value, path, allowedKeys) {
  validateOptionalRecord(value, path);
  const allowed = new Set(allowedKeys);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      throw new Error(`Invalid base JSON: unknown ${path} key ${key}`);
    }
  }
}

function validateOptionalRecord(value, path) {
  if (value !== undefined && !isRecord(value)) {
    throw new Error(`Invalid base JSON: ${path} must be an object when provided`);
  }
}

function validateOptionalString(value, path) {
  if (value !== undefined && typeof value !== 'string') {
    throw new Error(`Invalid base JSON: ${path} must be a string when provided`);
  }
}

function normalizeExplicitTimeZone(value) {
  const canonical = canonicalizeTimeZone(value);
  if (!canonical) {
    throw new Error('Invalid base JSON: site.timezone must be a non-blank valid IANA time zone or canonical ±HH:MM offset');
  }
  return canonical;
}

function normalizeLocale(value, path) {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`Invalid base JSON: ${path} must be a non-blank valid BCP 47 language tag`);
  }
  try {
    return Intl.getCanonicalLocales(value.trim())[0];
  } catch {
    throw new Error(`Invalid base JSON: ${path} must be a valid BCP 47 language tag`);
  }
}

function normalizeSiteOrigin(value, path) {
  if (typeof value !== 'string') {
    throw new Error(`Invalid base JSON: ${path} must be a string when provided`);
  }
  if (value.trim() === '') {
    return '';
  }

  const origin = normalizeHttpOrigin(value);
  if (!origin) {
    throw new Error(`Invalid base JSON: ${path} must be an absolute HTTP(S) origin without credentials, path, query, or fragment`);
  }
  return origin;
}

function normalizeCommentsApiBaseUrl(value, path) {
  if (typeof value !== 'string'
    || value.trim() === ''
    || value.trim() !== value
    || hasUnsafeUrlCharacters(value)) {
    throw new Error(`Invalid base JSON: ${path} must be an absolute HTTP(S) URL or root-relative path`);
  }
  if (hasCredentialAuthority(value) || hasQueryOrFragment(value)) {
    throw new Error(`Invalid base JSON: ${path} must not include credentials, query, or fragment`);
  }

  if (value.startsWith('/')) {
    if (value.startsWith('//')) {
      throw new Error(`Invalid base JSON: ${path} must be a safe root-relative path without query or fragment`);
    }
    return value === '/' ? '/' : value.replace(/\/+$/, '');
  }

  if (!parseSafeHttpUrl(value)) {
    throw new Error(`Invalid base JSON: ${path} must be HTTP(S) without credentials, query, or fragment`);
  }
  return value.replace(/\/+$/, '');
}

function validateOptionalBoolean(value, path) {
  if (value !== undefined && typeof value !== 'boolean') {
    throw new Error(`Invalid base JSON: ${path} must be a boolean when provided`);
  }
}

function validateOptionalInteger(value, path, { minimum, maximum = Number.POSITIVE_INFINITY }) {
  if (value === undefined) return;
  if (!Number.isInteger(value) || value < minimum || value > maximum) {
    const range = Number.isFinite(maximum) ? ` between ${minimum} and ${maximum}` : ` >= ${minimum}`;
    throw new Error(`Invalid base JSON: ${path} must be an integer${range}`);
  }
}

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}
